import { randomBytes } from 'node:crypto';
import { db } from './db';

/**
 * Tracked links: the first half of making the reporting true.
 *
 * Every analytics number in this product currently traces back to a fixture.
 * The claim the whole thing rests on — "this campaign generated N quote
 * requests" — has to be computed, and computing it starts here: a link per
 * *variation*, so a click can name the post that caused it.
 *
 * Per-variation, not per-campaign. A campaign-wide link answers "did the
 * campaign work"; only a per-post link answers "which post worked", which is
 * the question the learning loop in Phase 3 needs.
 */

/** Cookie holding the visitor id. First-party, no third-party anything. */
export const VISITOR_COOKIE = 'pcp_v';
/** Cookie holding the last click, so a conversion can be attributed to it. */
export const ATTRIBUTION_COOKIE = 'pcp_a';
/** Attribution window. Thirty days is the small-business decision cycle. */
export const ATTRIBUTION_MAX_AGE = 30 * 24 * 60 * 60;

/**
 * A short code. Base32-ish alphabet with no vowels and no look-alikes, since
 * these end up read aloud and typed by hand more often than you'd expect.
 */
const ALPHABET = '23456789bcdfghjkmnpqrstvwxyz';
export function newCode(length = 7): string {
  const bytes = randomBytes(length);
  let out = '';
  for (const b of bytes) out += ALPHABET[b % ALPHABET.length];
  return out;
}

/**
 * The link for a variation, minted on first use.
 *
 * Idempotent by design: publishing, previewing, and re-reading all want the
 * same URL, and a second link for the same post would split its own numbers.
 */
export async function linkFor(variation: {
  id: string;
  campaignId: string;
  cta: { url: string } | null;
}, fallbackUrl: string): Promise<{ code: string; targetUrl: string }> {
  const existing = await db.trackedLink.findUnique({ where: { variationId: variation.id } });
  if (existing) return { code: existing.code, targetUrl: existing.targetUrl };

  const targetUrl = variation.cta?.url || fallbackUrl;
  // A collision is vanishingly unlikely and cheap to survive, so retry rather
  // than reserve.
  for (let i = 0; i < 5; i++) {
    try {
      const link = await db.trackedLink.create({
        data: { code: newCode(), variationId: variation.id, campaignId: variation.campaignId, targetUrl },
      });
      return { code: link.code, targetUrl: link.targetUrl };
    } catch (e) {
      if (i === 4) throw e;
    }
  }
  throw new Error('could not mint a tracked link');
}

/**
 * Build the destination URL for a click: the target with UTMs appended.
 *
 * Existing query parameters on the target are preserved, and any UTM already
 * on it wins — if someone deliberately wrote `?utm_source=newsletter` into
 * their own link, overwriting it would be us second-guessing them.
 */
export function withUtms(
  targetUrl: string,
  utm: {
    campaign: string; source: string; medium: string; content?: string;
    /** The click id, which is how attribution survives to the customer's own
        domain without a cross-site cookie. */
    click?: string | null;
  }
): string {
  let url: URL;
  try {
    url = new URL(targetUrl);
  } catch {
    return targetUrl;
  }
  const set = (k: string, v: string | undefined) => {
    if (v && !url.searchParams.has(k)) url.searchParams.set(k, v);
  };
  set('utm_campaign', utm.campaign);
  set('utm_source', utm.source);
  set('utm_medium', utm.medium);
  set('utm_content', utm.content);
  // Our own parameter, not a UTM: analytics tools ignore it and the snippet
  // reads it. Named distinctly so it is obvious it isn't part of the standard.
  if (utm.click) set('pcp_click', utm.click);
  return url.toString();
}

/** Opaque, non-personal, and generated by us — never a fingerprint. */
export function newVisitorId(): string {
  return randomBytes(16).toString('base64url');
}
